### ISSUE TITLE
KSVD for Image Compression

### ISSUE THREAD

**Issue by Mahdidrm** [fubel/sparselandtools#1]
Hi everybody;
If you coded the KSVD algorithm for Image Compression in Python, could you please give me?  

Thanks and regards

**Comment by fubel** [comment]
Hi Mahdidrm, 

Which compression scheme are you interested in? A very simple approach would be to simply apply the image denoiser to an undisturbed image. The resulting image will be a compressed version of the original image.

Best regards,
Fabian

**Comment by Mahdidrm** [comment]
Hi Fubel;
Thanks for your answer, but I should implement KSVD in a over complete dictionary that contains the image patches; The KSVD algorithm is a dictionary learning method; In internet there are several image de-noising algorithms that using of KSVD; But I don't know how they are working in compression; 
Could you please give me some points and ideas?

**Comment by Mahdidrm** [comment]
> Hi Mahdidrm,
> 
> Which compression scheme are you interested in? A very simple approach would be to apply the image denoiser to an undisturbed image. The resulting image will be a compressed version of the original image.
> 
> Best regards,
> Fabian

Hi Fubel;
Thanks for your answer, but I should implement KSVD in a over complete dictionary that contains the image patches; The KSVD algorithm is a dictionary learning method; In internet there are several image de-noising algorithms that using of KSVD; But I don't know how they are working in compression;
Could you please give me some points and ideas?

**Comment by fubel** [comment]
The sparselandtool package offers something very similar. You should have a look at the denoising example in the Jupyter Notebook:
https://github.com/fubel/sparselandtools/blob/master/sparselandtools.ipynb

It uses the classes from here:
https://github.com/fubel/sparselandtools/blob/master/sparselandtools/applications/denoising.py 

In the example, K-SVD is used to generate an overcomplete dictionary from image patches. Instead of applying the denoiser to a noisy image, you could just apply it to a normal image. For sufficiently small sparsity, the reconstructed image will lose some of its higher / more complicated frequencies, which is a basic form of compression.

**Comment by Mahdidrm** [comment]
> The sparselandtool package offers something very similar. You should have a look at the denoising example in the Jupyter Notebook (last example, titled KSVD Image Denoising)
> https://github.com/fubel/sparselandtools/blob/master/sparselandtools.ipynb
> 
> It uses the classes from here:
> https://github.com/fubel/sparselandtools/blob/master/sparselandtools/applications/denoising.py
> 
> In the example, K-SVD is used to generate an overcomplete dictionary from image patches. Instead of applying the denoiser to a noisy image, you could just apply it to a normal image. For sufficiently small sparsity, the reconstructed image will lose some of its higher / more complicated frequencies, which is a basic form of compression.

Yes dear fubel; I found this package about 3 weeks ago; But I don't know how can import an image to the "denoising" code; Cod you please tellme how I can do this?

**Comment by fubel** [comment]
Use the `imageio` package to read in a gray image. Then follow the example from the notebook.

**Comment by Mahdidrm** [comment]
I wrote this code:

from sparselandtools.applications import KSVDImageDenoiser
from sparselandtools.dictionaries import DCTDictionary
from sparselandtools.pursuits import MatchingPursuit
import matplotlib.pyplot as plt
import imageio 


image = imageio.imread('1.tif') 
Dictionary = DCTDictionary(15, 20)
print("Initial an Overcomplete Dictionary")
plt.imshow(Dictionary.to_img())
plt.show()
a = KSVDImageDenoiser(Dictionary,MatchingPursuit)
imageio.imwrite('2.tif',a.image)

----------
but i received this error:
Image is not numeric, but NoneType.


------------
To saving the de-noised image what should i do?
