### ISSUE TITLE
How to install sparselandtools in linux/Ubuntu  with python 3.6.10 and Anaconda 4.5.12?

### ISSUE THREAD

**Issue by Mullahz** [fubel/sparselandtools#9]
Installation command "pip install sparselandtools" is not working in my linux conda environment.

**Comment by Mullahz** [comment]
[https://www.cnpython.com/pypi/sparselandtools](url)

**Comment by fubel** [comment]
I have updated the requirements.txt and now the travis pipeline builds successfully for Python 3.6:
https://travis-ci.com/github/fubel/sparselandtools/jobs/493146203 

Can you try installing the repository directly?

`
git clone https://github.com/fubel/sparselandtools.git
cd sparselandtools
pip install -e .
`

**Comment by Mullahz** [comment]
No, actually installing directly shows some error.
I have attached the screenshot for your reference.

Thank you.[
![sparselandtool](https://user-images.githubusercontent.com/10880413/112261761-7589a180-8c92-11eb-9133-476ac202cef1.PNG)
](url)

**Comment by fubel** [comment]
Your pip seems to be outdated. 

Try again after 

```
pip install --upgrade pip
```

**Comment by Mullahz** [comment]
Thank you.
It is done successfully after upgrading pip version to 21.0.1
